### ISSUE TITLE
Getting Class 'ZfcUserImpersonate\Module\AbstractModule' not found error

### ISSUE THREAD

**Issue by dshrestha** [mtudor/ZfcUserImpersonate#23]
I am trying to set up a zf2 project that uses ZfcUserImpersonate, but I am getting stuck with this error:

Fatal error: Class 'ZfcUserImpersonate\Module\AbstractModule' not found in  module\ZfcUserImpersonate\Module.php on line 16

I am not sure what I am missing, I have all the files in the vendor folder but the "use" doesn't seem to be able to include the AbstractModule.php file! 

Any suggestions on what I might have missed out??

Thanks,
Dee

**Comment by mtudor** [comment]
Hi Dee.  Not seen this one before.  My guess would have been a composer install that didn't quite go right, or perhaps something related to your environment.  What version of PHP are you on?

**Comment by dshrestha** [comment]
I was using wamp, with php ver 5.5.12. I was following the tutorial provided her e:http://framework.zend.com/manual/current/en/user-guide/skeleton-application.html to set up the vurtual host.

**Comment by mtudor** [comment]
Does ZfcUser work OK without ZfcUserImpersonate enabled?  You can login etc.?

**Comment by dshrestha** [comment]
Sorry to reopne this!! @mtudor what are the changes I need to do if I wanted to move ZfcUserImpersonate within my proj/module folder. The core reason why I was seeing the issue is its unable to include the Module.php file. 
So in ClassLoader.php, this function 


    /**
     * Loads the given class or interface.
     *
     * @param  string    $class The name of the class
     * @return bool|null True if loaded, null otherwise
     */
    public function loadClass($class)
    {
        echo 'class : '.$class.'<br>';
        if ($file = $this->findFile($class)) {
            echo 'file : '.$file.'<br>';
            includeFile($file);

            return true;
        }
    }

was throwing out the error. The output was :

class: ZfcUserImpersonate\Module 
file : C:\Programs\wamp\www\dshrestha\vendor/mtudor/zfc-user-impersonate/Module.php

Since the zfc-user-impersonate was moved, I need to tell zf to get these files from C:\Programs\wamp\www\dshrestha\module\ZfcUserImpersonate\Module.php instead. I am super new to zf so please bear with me for a bit :)

my personal guess is, its unable to include autoload_classmap.php when I moved the folder, so it doesn't know where to find the given classes. I looked into Module.php and was hoping to find something like getAutoloaderConfig() function but I didn't see that. HELPPP!!

**Comment by mtudor** [comment]
No worries - first off, let's address *why* you want to move this to your module directory instead of leaving it in vendor?  That will make updates with composer more difficult.

**Comment by dshrestha** [comment]
I was given pre-existing code. Literally I spent like 4 hrs reading up on zf2 and then looking at these code. I am wondering the developer working on it had to customize the view for login page(100% guess) and didn't want to put things in vendor - which makes sense to me because I wouldn't want to track history on anything in vendor folder(just personal taste).

**Comment by mtudor** [comment]
Ah the fun of pre-existing code!  ZF2 lets you override everything in modules in the vendor directory so you would not have to make changes there.  I'd suggest it would be best to leave the vendor code (ZfcUser, ZfcUserImpersonate etc. etc.) where it is and then read up on module / view overriding.  If you start altering vendor code then you're going to be in for a tough time when it comes to pulling updates to that module from the original author.

For example, we have ZfcUser in vendor and then we have a module in module directory called "TccUser" and that has all of our overrides in it.

**Comment by dshrestha** [comment]
thanks @mtudor for pointing me in right direction, I guess there is more reading for me.

**Comment by mtudor** [comment]
No worries - happy to help.  It can be a bit tricky when you first start out.  Try these to get you going:

https://juriansluiman.nl/article/117/use-3rd-party-modules-in-zend-framework-2

http://akrabat.com/overriding-module-configuration-in-zf2/
